"""Talk to GitHub in plain language.

Examples:
    "push it to github"                 (the last document created)
    "upload the ppt to my notes repo"
    "list my repos"
    "what files are in project-beastt"

Kept deliberately conservative: it only ever creates or updates a single file
under a dedicated folder, and never deletes or force-pushes anything.
"""

from __future__ import annotations

import re
from pathlib import Path

from .base import Skill

_PUSH = re.compile(
    r"\b(push|upload|commit|send|save)\b[^.?!]*\b(git\s?hub|repo|repository)\b", re.IGNORECASE
)
_LIST_REPOS = re.compile(
    r"\b(list|show|what are)\b[^.?!]*\b(my )?(repos|repositories)\b", re.IGNORECASE
)
_LIST_FILES = re.compile(
    r"\b(list|show|what)\b[^.?!]*\bfiles\b[^.?!]*?\b(?:in|of|from)\s+([\w.\-\/]+)", re.IGNORECASE
)
# "to my notes repo", "to klingesh/notes", "in the beastt repo"
_TARGET = re.compile(
    r"\b(?:to|into|in)\s+(?:my\s+|the\s+)?([\w.\-]+(?:/[\w.\-]+)?)\s*(?:repo|repository)?\b",
    re.IGNORECASE,
)
_STOPWORDS = {"github", "git", "hub", "repo", "repository", "my", "the", "it", "this", "that"}


class GitHubSkill(Skill):
    name = "github"

    def __init__(self, config, last_file_provider):
        self.config = config
        # Callable returning the most recently created document, if any.
        self._last_file = last_file_provider
        self._client = None

    # --- lifecycle --------------------------------------------------------
    def _get_client(self):
        if self._client is None:
            from ..github_client import GitHubClient

            self._client = GitHubClient(self.config.github_token)
        return self._client

    def matches(self, text: str) -> bool:
        return bool(_LIST_REPOS.search(text) or _LIST_FILES.search(text) or _PUSH.search(text))

    # --- actions ----------------------------------------------------------
    def run(self, text: str) -> str:
        from ..github_client import GitHubError

        client = self._get_client()
        if not client.configured:
            return (
                "I don't have GitHub access yet. Create a token at "
                "github.com/settings/tokens with 'repo' scope, then add this to your "
                ".env file:\n  BEASTT_GITHUB_TOKEN=your_token_here"
            )

        try:
            if _LIST_REPOS.search(text):
                return self._list_repos(client)
            match = _LIST_FILES.search(text)
            if match:
                return self._list_files(client, match.group(2))
            return self._push(client, text)
        except GitHubError as exc:
            return str(exc)
        except Exception as exc:
            return f"Something went wrong talking to GitHub ({exc.__class__.__name__}: {exc})."

    def _list_repos(self, client) -> str:
        repos = client.list_repos()
        if not repos:
            return "You don't have any repositories yet."
        lines = [
            f"- {r['name']}{' (private)' if r['private'] else ''}" for r in repos[:15]
        ]
        extra = "" if len(repos) <= 15 else f"\n...and {len(repos) - 15} more."
        return "Here are your most recently updated repos:\n" + "\n".join(lines) + extra

    def _list_files(self, client, repo: str) -> str:
        items = client.list_path(repo)
        if not items:
            return f"{repo} looks empty."
        lines = []
        for item in items[:20]:
            marker = "/" if item["type"] == "dir" else ""
            lines.append(f"- {item['name']}{marker}")
        extra = "" if len(items) <= 20 else f"\n...and {len(items) - 20} more."
        return f"Top level of {repo}:\n" + "\n".join(lines) + extra

    def _resolve_target(self, text: str) -> str:
        """Work out which repo to push to."""
        for match in _TARGET.finditer(text):
            candidate = match.group(1).strip()
            if candidate.lower() not in _STOPWORDS and len(candidate) > 1:
                return candidate
        return self.config.github_repo

    def _push(self, client, text: str) -> str:
        path = self._last_file()
        if not path:
            return (
                "I don't have a file ready to push yet. Ask me to make a document "
                "first -- for example, \"make a ppt about renewable energy\"."
            )
        path = Path(path)
        repo = self._resolve_target(text)
        if not repo:
            return (
                f"Which repository should I push {path.name} to? You can also set a "
                "default with BEASTT_GITHUB_REPO in .env."
            )

        print(f"[github] Pushing {path.name} to {repo}...")
        result = client.push_file(
            repo,
            path,
            remote_path=f"{self.config.github_folder.strip('/')}/{path.name}"
            if self.config.github_folder
            else path.name,
            message=f"Add {path.name} (generated by {self.config.name})",
        )
        verb = "Updated" if result["updated"] else "Pushed"
        return (
            f"{verb} {path.name} to {result['repo']} on branch {result['branch']}.\n"
            f"{result['url']}"
        )
